# Generated by Django 3.1.5 on 2021-01-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20210126_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
