# Generated by Django 3.1.5 on 2021-01-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_quote_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='internal_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
