# Generated by Django 3.1.5 on 2021-01-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_quote_internal_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='note',
            new_name='terms',
        ),
        migrations.CreateModel(
            name='quotedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_product', to='quote.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_quote', to='quote.quote')),
            ],
        ),
    ]
