# Generated by Django 3.1.5 on 2021-01-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_auto_20210129_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedproducts',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
