# Generated by Django 3.1.5 on 2021-01-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_quotedproducts_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotedproducts',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
