# Generated by Django 3.1.5 on 2021-01-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_auto_20210131_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='shipping',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
