# Generated by Django 3.1.5 on 2021-02-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_quote_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotedproduct',
            old_name='custom_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='quotedproduct',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
