# Generated by Django 3.1.5 on 2021-02-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0014_auto_20210204_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
