# Generated by Django 3.1.5 on 2021-02-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0015_company_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='short_description',
            new_name='description',
        ),
    ]
