# Generated by Django 3.1.6 on 2021-02-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0016_auto_20210204_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='shipping',
        ),
    ]
