# Generated by Django 3.1.6 on 2021-02-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0017_remove_quote_shipping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompany',
            options={'verbose_name_plural': 'Users Companies'},
        ),
    ]
