# Generated by Django 3.1.6 on 2021-02-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0020_auto_20210206_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='legal_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
