# Generated by Django 3.1.6 on 2021-02-15 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0023_auto_20210215_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
